### ISSUE TITLE
vanilla setup yields TypeError; doesn't start at all

### ISSUE THREAD

**Issue by andreemic** [bananaml/banana-cli#15]
`banana init` in a clean folder first yields an install error 
```
...
Collecting zipp>=0.5
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Building wheels for collected packages: lit
  Building wheel for lit (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/whisper-wordtimestamps/banana/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i761ji9r/lit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i761ji9r/lit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_gue7qv_
       cwd: /tmp/pip-install-i761ji9r/lit/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for lit
...
```

and then 

```
...
🍌 Project ready to go (hurrah!)

🔥 To run a dev server with hot-reload, run:
banana dev
(venv) ubuntu@165-1-79-47:~/whisper-wordtimestamps/banana$ banana dev
------
Starting server 🍌
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/banana", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/banana_cli/cli.py", line 62, in dev
    run_dev_server(app_path, site_packages, auto_compat)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/banana_cli/cmd_dev.py", line 164, in run_dev_server
    start_all(b1, b2, first_run)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/banana_cli/cmd_dev.py", line 94, in start_all
    run_cell(b1)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/banana_cli/process/run.py", line 3, in run_cell
    exec(input_file, globals())
  File "<string>", line 1, in <module>
  File "/home/ubuntu/whisper-wordtimestamps/banana/venv/lib/python3.8/site-packages/potassium/__init__.py", line 1, in <module>
    from .potassium import *
  File "/home/ubuntu/whisper-wordtimestamps/banana/venv/lib/python3.8/site-packages/potassium/potassium.py", line 2, in <module>
    from flask import Flask
  File "/home/ubuntu/whisper-wordtimestamps/banana/venv/lib/python3.8/site-packages/flask/__init__.py", line 1, in <module>
    from . import json as json
  File "/home/ubuntu/whisper-wordtimestamps/banana/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 6, in <module>
    from ..globals import current_app
  File "/home/ubuntu/whisper-wordtimestamps/banana/venv/lib/python3.8/site-packages/flask/globals.py", line 45, in <module>
    app_ctx: AppContext = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'
```

If I add "flask==2.1.3" as recommended on [SO](https://stackoverflow.com/questions/73337927/typeerror-init-got-an-unexpected-keyword-argument-unbound-message), another error appears at run time because "get_json" is not defined on the flask request obejct (they didn't have that api yet i guess).

**Comment by nik-418** [comment]
Recent updates should have fixed this. 👍
